### ISSUE TITLE
It seems that all sponsors listed in interests.yaml/languages.yaml are marked as active

### ISSUE THREAD

**Issue by hroncok** [FrostyX/fedora-sponsors#16]
Is that assumption correct?

I see sponsors marked [as active](https://docs.pagure.org/fedora-sponsors/active) that were not active in Fedora for years. Maybe they secretly do package reviews and sponsorships but nothing else, but that sounds unrealistic.

**Comment by FrostyX** [comment]
Thank you for the report @hroncok,
I understand that it may be a bit sensitive but can you please name such a person/people? Feel free to ping me privately if you don't want to name-drop people here.

We have an `activity.py` script in this repo that decides who should be listed as active or inactive. I can run it and show you its reasoning why the person was marked as active. Maybe it has some false positives.

**Comment by hroncok** [comment]
Try ralph.

**Comment by hroncok** [comment]
Hello again. Could you see why ralph is marked as active?

**Comment by FrostyX** [comment]
Sure @hroncok,
sorry, I must have missed your previous message.

**Comment by FrostyX** [comment]
There was deployed an older build of the page because the rebuild mechanism was stuck. I did it manually and now `ralph` is marked as inactive. There is no way of knowing what marked him as active before. We will need to keep an aye on him if he appears active again or we need to try to debug another person.

**Comment by hroncok** [comment]
Thanks.
